const fs = require('fs');
const path = require('path');

const workspaceRoot = path.resolve(__dirname, '../../.openclaw/workspace');

function getOpenClawName() {
  try {
    const content = fs.readFileSync(path.join(workspaceRoot, 'SOUL.md'), 'utf-8');
    const match = content.match(/^# SOUL.md - Who I Am\s*\n\s*I'm ([^\.]+)/);
    return match ? match[1].trim() : 'Sebastian';
  } catch (e) { return 'Sebastian'; }
}

function getHumanName() {
  try {
    const content = fs.readFileSync(path.join(workspaceRoot, 'USER.md'), 'utf-8');
    const match = content.match(/- \*\*Name:\*\* ([^\n]+)/);
    return match ? match[1].trim() : 'Michael';
  } catch (e) { return 'Michael'; }
}

const humanName = getHumanName();
const aiName = getOpenClawName();

const config = `// Auto-generated by scripts/generate-users.js - DO NOT EDIT
// Regenerate with: node scripts/generate-users.js

export const users = [
  { id: '${humanName}', name: '${humanName}', color: '#3b82f6' },
  { id: '${aiName}', name: '${aiName}', color: '#a855f7' }
];

export const currentUser = '${humanName}';

export const getUserColor = (userId) => {
  const user = users.find(u => u.id === userId);
  return user ? user.color : '#6b7280';
};

export const getUserInitials = (userId) => {
  const user = users.find(u => u.id === userId);
  return user ? user.name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2) : '??';
};
`;

fs.writeFileSync(path.join(__dirname, '../src/config/users.js'), config);
console.log(`Generated users.js - Human: ${humanName}, AI: ${aiName}`);
