// Auto-generated by scripts/generate-users.js - DO NOT EDIT
// Regenerate with: node scripts/generate-users.js

export const users = [
  { id: 'Michael', name: 'Michael', color: '#3b82f6' },
  { id: 'Sebastian', name: 'Sebastian', color: '#a855f7' }
];

export const currentUser = 'Michael';

export const getUserColor = (userId) => {
  const user = users.find(u => u.id === userId);
  return user ? user.color : '#6b7280';
};

export const getUserInitials = (userId) => {
  const user = users.find(u => u.id === userId);
  return user ? user.name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2) : '??';
};
